### ISSUE TITLE
.faa misformatted or empty issue in the Step 1.

### ISSUE THREAD

**Issue by AMBL-CW** [mtisza1/DNA_methylase_finder#2]
Hello! 

Thank you for developing this useful and convenient tool. The installation process was also very easy. 
After installation, I tried using the command you provided, but I encountered an issue at Step 1. 
This problem occurs not only with the command you provided but also when I try using my own .fna file as input. 
Could you explain why this might be happening? 

I'd like to know what the issue is and get started with this great tool as soon as possible for finding DNA methylases in prokaryotes. 
Below is the code I used and the result.

```
(dna_methylase_finder) cw@PEL-WS:~$ python DNA_methylase_finder/run_DNA_methylase_finder.py -it AA -f DNA_methylase_finder/test_seqs/mtases_GCA_016889925.1.faa -r TEST_AAs
/home/cw/DNA_methylase_finder
/home/cw/DNA_methylase_finder/run_DNA_methylase_finder.py:56: DeprecationWarning: Use shutil.which instead of find_executable
  return find_executable(name) is not None
bioawk found
hmmscan found
blastp found
prodigal found
Biopython found
BCBio found
numpy found
DNA Methylase Finder!
Version 1.0.1
A seemingly good .faa file found. Continuing
Step 1. Splitting AA file for parallelization -- 08-20-24---10:58:42
/home/cw/DNA_methylase_finder/DNA_methylase_finder_v1.0.sh: line 90: bc: command not found
/home/cw/DNA_methylase_finder/DNA_methylase_finder_v1.0.sh: line 91: [: -ge: unary operator expected
is mtases_GCA_016889925.1.faa misformatted or empty? Exiting.
```

**Comment by mtisza1** [comment]
Hi,

Thanks for opening the issue. It looks like your system doesn't have `bc` installed.

After activating your dna_methylase_finder conda environment, use this command: 

`conda install conda-forge::bc`

I think you'll be good to go after that!

**Comment by AMBL-CW** [comment]
Oh, thanks! It's working well now.

Thanks to your reply, I was able to fix the issue really easily.

Have a great day!
